In [ ]:
# Tensorflow 2.0
# Sequential API
## 모델 구축

In [1]:
# 간단한 형태의 완전 연결 계층 (fully-connected layer)
from tensorflow.keras import layers

In [3]:
import tensorflow as tf

In [4]:
model = tf.keras.Sequential()
model.add(layers.Dense(64, activation='relu'))

In [5]:
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

In [6]:
# Functional API

In [7]:
inputs = tf.keras.Input(shape=(32,))
x = layers.Dense(64, activation='relu')(inputs)
x = layers.Dense(64, activation='relu')(x)
predictions = layers.Dense(10, activation='softmax')(x)

In [8]:
# Custom Layer
# 새로운 연산을 하는 레이어 혹은 편의를 위해 여러 레이어를 하나로 묶은 레이어를 구현해야 하는 경우가 있다.
# 이때 사용자 정의 층(custom layer)을 만들어 사용. dense 층이 여러 번 사용된 신경망을 사용하였다.

class CustomLayer(layers.Layer):

  def __init__(self, hidden_dimension, hidden_dimension2, output_dimension):
    self.hidden_dimension = hidden_dimension
    self.hidden_dimension2 = hidden_dimension2
    self.output_dimension = output_dimension
    super(CustomLayer, self).__init__()

  def build(self, input_shape):
    self.dense_layer1 = layers.Dense(self.hidden_dimension, activation='relu')
    self.dense_layer2 = layers.Dense(self.hidden_dimension2, activation='relu')
    self.dense_layer3 = layers.Dense(self.output_dimension, activation='softmax')

  def call(self, inputs):
    x = self.dense_layer1(inputs)
    x = self.dense_layer2(x)

    return self.dense_layer3(x)

In [9]:
# Sequential API나 Functional API를 활용할 때 하나의 층으로 사용할 수 있다.
# 만약 Sequential 모듈을 활용한다면 다음과 같이 사용.

from tensorflow.keras import layers

model = tf.keras.Sequential()
model.add(CustomLayer(64, 64, 10))

In [11]:
# Subclassing (Custom Model)
# 계속 다루게 될 자연어처리 책에서도 많이 활용하는 방법이자 가장 자유도가 높은 모델

class MyModel(tf.keras.Model):
    
    def __init__(self, hidden_dimension, hidden_dimension2, output_dimension):
      super(MyModel, self).__init__(name='my model')
      self.dense_layer1 = layers.Dense(hidden_dimension, activation = 'relu')
      self.dense_layer2 = layers.Dense(hidden_dimension2, activation = 'relu')
      self.dense_layer3 = layers.Dense(output_dimension, activation = 'softmax')

    def call(self, inputs):
      x = self.dense_layer1(inputs)
      x = self.dense_layer2(x)

      return self.dense_layer3(x)

In [12]:
## 모델 학습 
# 케라스 모델의 내장 API 활용

# 학습 과정에서 사용될 손실 함수(loss function), 옵티마이저(optimizer), 지표(metric)

model.compile(optimizer=tf.keras.optimizers.Adam(),
              loss=tf.keras.losses.CategoricalCrossentropy(),
              metrics=[tf.keras.metrics.Accuracy()])

In [13]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [15]:
## 더미 데이터를 활용한 감정 분석 모델링
# 심층 신경망 구조를 사용해 앞서 텍스트의 긍정/부정을 예측하는 감정 분석 모델.

import tensorflow as tf
from tensorflow.keras import preprocessing

samples = ['너 오늘 이뻐 보인다',
           '나는 오늘 기분이 더러워',
           '끝내주는데, 좋은 일이 있나봐',
           '나 좋은 일이 생겼어',
           '아 오늘 진짜 짜증나',
           '환상적인데, 정말 좋은거 같아']

labels = [[1], [0], [1], [1], [0], [1]]
tokenizer = preprocessing.text.Tokenizer()
tokenizer.fit_on_texts(samples)
sequences = tokenizer.texts_to_sequences(samples)

word_index = tokenizer.word_index

In [16]:
batch_size = 2
num_epochs = 100
vocab_size = len(word_index) + 1
emb_size = 128
hidden_dimension = 256
output_dimension = 1

# 3장에서 계속 진행할 것 ..

In [ ]:
## 사이킷런

In [17]:
from sklearn.datasets import load_iris

In [18]:
iris_dataset = load_iris()
print("iris_dataset key : {}".format(iris_dataset.keys()))

iris_dataset key : dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [19]:
print(iris_dataset['data'])
print("shape of data : {}".format(iris_dataset['data'].shape))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [20]:
print(iris_dataset['feature_names'])

# 꽃의 꽃받침 길이, 꽃받침 너비, 꽃잎 길이, 꽃잎 너비

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [21]:
print(iris_dataset['target'])
print(iris_dataset['target_names'])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


In [22]:
print(iris_dataset['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
train_input, test_input, train_label, test_label = train_test_split(iris_dataset['data'], iris_dataset['target'], test_size=0.25,
                                                                    random_state=42)

In [27]:
print("shape of train_input : {}".format(train_input.shape))
print("shape of test_input : {}".format(test_input.shape))
print("shape of train_label : {}".format(train_label.shape))
print("shape of test_label : {}".format(test_label.shape))

shape of train_input : (112, 4)
shape of test_input : (38, 4)
shape of train_label : (112,)
shape of test_label : (38,)
